version: '3.3'
 
services:
  hurado-main:
    container_name: hurado-main
    image: noiph/hurado:latest
    working_dir: /app
    command: npm run dev
    environment:
      - IS_UNDER_DOCKER=true
    env_file:
      - .env
    ports:
      - 10000:10000
    restart: always
    depends_on:
      - hurado-postgres
    links:
      - hurado-postgres
    volumes:
      - ./:/app/
  hurado-judge:
    container_name: hurado-judge
    image: noiph/hurado:latest
    privileged: true
    working_dir: /app
    command: npm run dev:worker
    environment:
      - IS_UNDER_DOCKER=true
    env_file:
      - .env
    restart: always
    depends_on:
      - hurado-postgres
    links:
      - hurado-postgres
    volumes:
      - ./:/app/
  hurado-postgres:
    container_name: hurado-postgres
    image: postgres:17-alpine
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data/
  hurado-redis:
    container_name: hurado-redis
    image: redis:7-alpine
    ports:
      - "6379"  # Blob service
    volumes:
      - ./volumes/redis:/data
  hurado-minio:
    container_name: hurado-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=hurado
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
