version: '3.3'
 
services:
  hurado-main:
    container_name: hurado-main
    image: noiph/hurado:latest
    working_dir: /app
    command: node /app/.next/standalone/server.js
    environment:
      - IS_UNDER_DOCKER=true
    env_file:
      - .env
    ports:
      - 10000:10000
    restart: always
    depends_on:
      - hurado-postgres
    links:
      - hurado-postgres
    volumes:
      - .:/app
  hurado-judge:
    container_name: hurado-judge
    image: noiph/hurado:latest
    privileged: true
    working_dir: /app
    command: npm run worker
    environment:
      - IS_UNDER_DOCKER=true
    env_file:
      - .env
    restart: always
    depends_on:
      - hurado-postgres
    links:
      - hurado-postgres
    volumes:
      - ./:/app/
  hurado-postgres:
    container_name: hurado-postgres
    image: postgres:17-alpine
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data/
  hurado-redis:
    container_name: hurado-redis
    image: redis:7-alpine
    ports:
      - "6379"
    volumes:
      - ./volumes/redis:/data
  hurado-nginx:
    container_name: hurado-nginx
    image: nginx:1-alpine
    ports:
      - "443:443"
    volumes:
      - ./config/production/nginx/:/etc/nginx/
      - ./private/nginx-certs/:/etc/nginx-certs/
      - ./.next/:/var/www/hurado/:ro
